// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef _VITMITATRONICS_UI_H
#define _VITMITATRONICS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_home.h"
#include "screens/ui_choose.h"
#include "screens/ui_payment.h"
#include "screens/ui_preparing.h"
#include "screens/ui_success.h"
#include "screens/ui_config.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1238612230);    // assets/VITcc-Logo-June25.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png
LV_IMG_DECLARE(ui_img_config_png);    // assets/config.png
LV_IMG_DECLARE(ui_img_chevron_png);    // assets/chevron.png
LV_IMG_DECLARE(
    ui_img_stockpot_64dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/stockpot_64dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_yoshoku_132dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/yoshoku_132dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(ui_img_cooking_png);    // assets/cooking.png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png

// FONTS
LV_FONT_DECLARE(ui_font_LoraRegular24);
LV_FONT_DECLARE(ui_font_LoraRegular40);
LV_FONT_DECLARE(ui_font_LoraRegular64);
LV_FONT_DECLARE(ui_font_OpenSansBold14);
LV_FONT_DECLARE(ui_font_OpenSansBold20);
LV_FONT_DECLARE(ui_font_OpenSansRegular16);
LV_FONT_DECLARE(ui_font_OpenSansRegular20);
LV_FONT_DECLARE(ui_font_OpenSansSemiBold16);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
