// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void homeConfigClicked(lv_event_t * e);
void chooseButton1Clicked(lv_event_t * e);
void chooseButton2Clicked(lv_event_t * e);
void chooseBackButtonClicked(lv_event_t * e);
void paymentBackButtonClicked(lv_event_t * e);
void preparingCancelButtonClicked(lv_event_t * e);
void successPanelButtonClicked(lv_event_t * e);
void configButtonEspressoClicked(lv_event_t * e);
void configButtonCoffeeClicked(lv_event_t * e);
void configButtonResetClicked(lv_event_t * e);
void configButtonBackClicked(lv_event_t * e);
void configButtonRestartClicked(lv_event_t * e);
void configPasswordKeyboardValueChanged(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
