// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#include "../ui.h"

lv_obj_t * ui_choose = NULL;
lv_obj_t * ui_choosePanel1 = NULL;
lv_obj_t * ui_choosePanel1Button = NULL;
lv_obj_t * ui_choosePanel1ButtonLabel = NULL;
lv_obj_t * ui_choosePanel1Title = NULL;
lv_obj_t * ui_choosePanel1PriceLabel = NULL;
lv_obj_t * ui_choosePanel1PriceContainerTop = NULL;
lv_obj_t * ui_choosePanel1PriceSats = NULL;
lv_obj_t * ui_choosePanel1PriceBrl = NULL;
lv_obj_t * ui_choosePanel1PriceContainerBottom = NULL;
lv_obj_t * ui_choosePanel2 = NULL;
lv_obj_t * ui_choosePanel2Button = NULL;
lv_obj_t * ui_choosePanel2ButtonLabel = NULL;
lv_obj_t * ui_choosePanel2Title = NULL;
lv_obj_t * ui_choosePanel2PriceLabel = NULL;
lv_obj_t * ui_choosePanel2PriceContainerTop = NULL;
lv_obj_t * ui_choosePanel2PriceSats = NULL;
lv_obj_t * ui_choosePanel2PriceBrl = NULL;
lv_obj_t * ui_choosePanel2PriceContainerBottom = NULL;
lv_obj_t * ui_chooseBack = NULL;
lv_obj_t * ui_chooseLogo = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
// event funtions
void ui_event_choosePanel1Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        chooseButton1Clicked(e);
    }
}

void ui_event_choosePanel2Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        chooseButton2Clicked(e);
    }
}

void ui_event_chooseBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        chooseBackButtonClicked(e);
    }
}

void ui_event_chooseLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_choose, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_choose_screen_init);
    }
}

// build funtions

void ui_choose_screen_init(void)
{
    ui_choose = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_choose, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choose, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1 = lv_obj_create(ui_choose);
    lv_obj_set_width(ui_choosePanel1, 360);
    lv_obj_set_height(ui_choosePanel1, 372);
    lv_obj_set_x(ui_choosePanel1, 24);
    lv_obj_set_y(ui_choosePanel1, 80);
    lv_obj_clear_flag(ui_choosePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_choosePanel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_choosePanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choosePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_choosePanel1, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_choosePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_choosePanel1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_choosePanel1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_choosePanel1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_choosePanel1, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1Button = lv_btn_create(ui_choosePanel1);
    lv_obj_set_width(ui_choosePanel1Button, 328);
    lv_obj_set_height(ui_choosePanel1Button, 44);
    lv_obj_set_x(ui_choosePanel1Button, -3);
    lv_obj_set_y(ui_choosePanel1Button, 294);
    lv_obj_set_align(ui_choosePanel1Button, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_choosePanel1Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_choosePanel1Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_choosePanel1Button, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_choosePanel1Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choosePanel1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_choosePanel1Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel1Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_choosePanel1Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel1Button, &ui_font_OpenSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1ButtonLabel = lv_label_create(ui_choosePanel1Button);
    lv_obj_set_width(ui_choosePanel1ButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel1ButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_choosePanel1ButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_choosePanel1ButtonLabel, "Order Masoor Dal");
    lv_obj_set_style_text_color(ui_choosePanel1ButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel1ButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel1ButtonLabel, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1Title = lv_label_create(ui_choosePanel1);
    lv_obj_set_width(ui_choosePanel1Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel1Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel1Title, 0);
    lv_obj_set_y(ui_choosePanel1Title, 142);
    lv_obj_set_align(ui_choosePanel1Title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_choosePanel1Title, "Masoor Dal");
    lv_obj_set_style_text_color(ui_choosePanel1Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel1Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel1Title, &ui_font_LoraRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1PriceLabel = lv_label_create(ui_choosePanel1);
    lv_obj_set_width(ui_choosePanel1PriceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel1PriceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel1PriceLabel, 0);
    lv_obj_set_y(ui_choosePanel1PriceLabel, 200);
    lv_label_set_text(ui_choosePanel1PriceLabel, "Price");
    lv_obj_set_style_text_color(ui_choosePanel1PriceLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel1PriceLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel1PriceLabel, &ui_font_OpenSansSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1PriceContainerTop = lv_obj_create(ui_choosePanel1);
    lv_obj_remove_style_all(ui_choosePanel1PriceContainerTop);
    lv_obj_set_width(ui_choosePanel1PriceContainerTop, 326);
    lv_obj_set_height(ui_choosePanel1PriceContainerTop, 52);
    lv_obj_set_x(ui_choosePanel1PriceContainerTop, 0);
    lv_obj_set_y(ui_choosePanel1PriceContainerTop, 230);
    lv_obj_set_align(ui_choosePanel1PriceContainerTop, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_choosePanel1PriceContainerTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_choosePanel1PriceContainerTop, lv_color_hex(0x333333),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_choosePanel1PriceContainerTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_choosePanel1PriceContainerTop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_choosePanel1PriceContainerTop, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_choosePanel1PriceContainerTop, lv_color_hex(0x333333),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_choosePanel1PriceContainerTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1PriceSats = lv_label_create(ui_choosePanel1);
    lv_obj_set_width(ui_choosePanel1PriceSats, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel1PriceSats, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel1PriceSats, 0);
    lv_obj_set_y(ui_choosePanel1PriceSats, 246);
    lv_label_set_text(ui_choosePanel1PriceSats, "1.414 sats");
    lv_obj_add_flag(ui_choosePanel1PriceSats, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_choosePanel1PriceSats, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel1PriceSats, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel1PriceSats, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1PriceBrl = lv_label_create(ui_choosePanel1);
    lv_obj_set_width(ui_choosePanel1PriceBrl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel1PriceBrl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel1PriceBrl, 0);
    lv_obj_set_y(ui_choosePanel1PriceBrl, 246);
    lv_obj_set_align(ui_choosePanel1PriceBrl, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_choosePanel1PriceBrl, "Rs. 150");
    lv_obj_set_style_text_color(ui_choosePanel1PriceBrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel1PriceBrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel1PriceBrl, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel1PriceContainerBottom = lv_obj_create(ui_choosePanel1);
    lv_obj_remove_style_all(ui_choosePanel1PriceContainerBottom);
    lv_obj_set_width(ui_choosePanel1PriceContainerBottom, 326);
    lv_obj_set_height(ui_choosePanel1PriceContainerBottom, 52);
    lv_obj_set_x(ui_choosePanel1PriceContainerBottom, 0);
    lv_obj_set_y(ui_choosePanel1PriceContainerBottom, 230);
    lv_obj_set_align(ui_choosePanel1PriceContainerBottom, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_choosePanel1PriceContainerBottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_choosePanel1PriceContainerBottom, lv_color_hex(0x333333),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_choosePanel1PriceContainerBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_choosePanel1PriceContainerBottom, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_choosePanel1PriceContainerBottom, LV_BORDER_SIDE_BOTTOM,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_choosePanel1PriceContainerBottom, lv_color_hex(0x333333),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_choosePanel1PriceContainerBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2 = lv_obj_create(ui_choose);
    lv_obj_set_width(ui_choosePanel2, 360);
    lv_obj_set_height(ui_choosePanel2, 372);
    lv_obj_set_x(ui_choosePanel2, -25);
    lv_obj_set_y(ui_choosePanel2, 80);
    lv_obj_set_align(ui_choosePanel2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_choosePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_choosePanel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_choosePanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choosePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_choosePanel2, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_choosePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_choosePanel2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_choosePanel2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_choosePanel2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_choosePanel2, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2Button = lv_btn_create(ui_choosePanel2);
    lv_obj_set_width(ui_choosePanel2Button, 328);
    lv_obj_set_height(ui_choosePanel2Button, 44);
    lv_obj_set_x(ui_choosePanel2Button, -3);
    lv_obj_set_y(ui_choosePanel2Button, 294);
    lv_obj_set_align(ui_choosePanel2Button, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_choosePanel2Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_choosePanel2Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_choosePanel2Button, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_choosePanel2Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_choosePanel2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_choosePanel2Button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel2Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_choosePanel2Button, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel2Button, &ui_font_OpenSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2ButtonLabel = lv_label_create(ui_choosePanel2Button);
    lv_obj_set_width(ui_choosePanel2ButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel2ButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_choosePanel2ButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_choosePanel2ButtonLabel, "Order Tomato Soup");
    lv_obj_set_style_text_color(ui_choosePanel2ButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel2ButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel2ButtonLabel, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2Title = lv_label_create(ui_choosePanel2);
    lv_obj_set_width(ui_choosePanel2Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel2Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel2Title, 0);
    lv_obj_set_y(ui_choosePanel2Title, 142);
    lv_obj_set_align(ui_choosePanel2Title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_choosePanel2Title, "Tomato Soup");
    lv_obj_set_style_text_color(ui_choosePanel2Title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel2Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel2Title, &ui_font_LoraRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2PriceLabel = lv_label_create(ui_choosePanel2);
    lv_obj_set_width(ui_choosePanel2PriceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel2PriceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel2PriceLabel, 0);
    lv_obj_set_y(ui_choosePanel2PriceLabel, 200);
    lv_label_set_text(ui_choosePanel2PriceLabel, "Price");
    lv_obj_set_style_text_color(ui_choosePanel2PriceLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel2PriceLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel2PriceLabel, &ui_font_OpenSansSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2PriceContainerTop = lv_obj_create(ui_choosePanel2);
    lv_obj_remove_style_all(ui_choosePanel2PriceContainerTop);
    lv_obj_set_width(ui_choosePanel2PriceContainerTop, 328);
    lv_obj_set_height(ui_choosePanel2PriceContainerTop, 52);
    lv_obj_set_x(ui_choosePanel2PriceContainerTop, 0);
    lv_obj_set_y(ui_choosePanel2PriceContainerTop, 230);
    lv_obj_set_align(ui_choosePanel2PriceContainerTop, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_choosePanel2PriceContainerTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_choosePanel2PriceContainerTop, lv_color_hex(0x333333),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_choosePanel2PriceContainerTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_choosePanel2PriceContainerTop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_choosePanel2PriceContainerTop, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_choosePanel2PriceContainerTop, lv_color_hex(0x333333),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_choosePanel2PriceContainerTop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2PriceSats = lv_label_create(ui_choosePanel2);
    lv_obj_set_width(ui_choosePanel2PriceSats, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel2PriceSats, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel2PriceSats, 0);
    lv_obj_set_y(ui_choosePanel2PriceSats, 246);
    lv_label_set_text(ui_choosePanel2PriceSats, "1.414 sats");
    lv_obj_add_flag(ui_choosePanel2PriceSats, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_choosePanel2PriceSats, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel2PriceSats, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel2PriceSats, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2PriceBrl = lv_label_create(ui_choosePanel2);
    lv_obj_set_width(ui_choosePanel2PriceBrl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_choosePanel2PriceBrl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_choosePanel2PriceBrl, 0);
    lv_obj_set_y(ui_choosePanel2PriceBrl, 246);
    lv_obj_set_align(ui_choosePanel2PriceBrl, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_choosePanel2PriceBrl, "Rs. 100");
    lv_obj_set_style_text_color(ui_choosePanel2PriceBrl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_choosePanel2PriceBrl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_choosePanel2PriceBrl, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_choosePanel2PriceContainerBottom = lv_obj_create(ui_choosePanel2);
    lv_obj_remove_style_all(ui_choosePanel2PriceContainerBottom);
    lv_obj_set_width(ui_choosePanel2PriceContainerBottom, 326);
    lv_obj_set_height(ui_choosePanel2PriceContainerBottom, 52);
    lv_obj_set_x(ui_choosePanel2PriceContainerBottom, 0);
    lv_obj_set_y(ui_choosePanel2PriceContainerBottom, 230);
    lv_obj_set_align(ui_choosePanel2PriceContainerBottom, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_choosePanel2PriceContainerBottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_choosePanel2PriceContainerBottom, lv_color_hex(0x333333),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_choosePanel2PriceContainerBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_choosePanel2PriceContainerBottom, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_choosePanel2PriceContainerBottom, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_choosePanel2PriceContainerBottom, lv_color_hex(0x333333),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_choosePanel2PriceContainerBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chooseBack = lv_imgbtn_create(ui_choose);
    lv_imgbtn_set_src(ui_chooseBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_chevron_png, NULL);
    lv_imgbtn_set_src(ui_chooseBack, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_chevron_png, NULL);
    lv_obj_set_width(ui_chooseBack, 48);
    lv_obj_set_height(ui_chooseBack, 48);
    lv_obj_set_x(ui_chooseBack, -352);
    lv_obj_set_y(ui_chooseBack, -200);
    lv_obj_set_align(ui_chooseBack, LV_ALIGN_CENTER);

    ui_chooseLogo = lv_img_create(ui_choose);
    lv_img_set_src(ui_chooseLogo, &ui_img_1238612230);
    lv_obj_set_width(ui_chooseLogo, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_chooseLogo, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_chooseLogo, 505);
    lv_obj_set_y(ui_chooseLogo, -52);
    lv_obj_add_flag(ui_chooseLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_chooseLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_chooseLogo, 64);

    ui_Image1 = lv_img_create(ui_choose);
    lv_img_set_src(ui_Image1, &ui_img_stockpot_64dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image1, 193);
    lv_obj_set_y(ui_Image1, -64);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 512);

    ui_Image2 = lv_img_create(ui_choose);
    lv_img_set_src(ui_Image2, &ui_img_yoshoku_132dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 132
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 132
    lv_obj_set_x(ui_Image2, -200);
    lv_obj_set_y(ui_Image2, -70);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_choosePanel1Button, ui_event_choosePanel1Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_choosePanel2Button, ui_event_choosePanel2Button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chooseBack, ui_event_chooseBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_chooseLogo, ui_event_chooseLogo, LV_EVENT_ALL, NULL);

}

void ui_choose_screen_destroy(void)
{
    if(ui_choose) lv_obj_del(ui_choose);

    // NULL screen variables
    ui_choose = NULL;
    ui_choosePanel1 = NULL;
    ui_choosePanel1Button = NULL;
    ui_choosePanel1ButtonLabel = NULL;
    ui_choosePanel1Title = NULL;
    ui_choosePanel1PriceLabel = NULL;
    ui_choosePanel1PriceContainerTop = NULL;
    ui_choosePanel1PriceSats = NULL;
    ui_choosePanel1PriceBrl = NULL;
    ui_choosePanel1PriceContainerBottom = NULL;
    ui_choosePanel2 = NULL;
    ui_choosePanel2Button = NULL;
    ui_choosePanel2ButtonLabel = NULL;
    ui_choosePanel2Title = NULL;
    ui_choosePanel2PriceLabel = NULL;
    ui_choosePanel2PriceContainerTop = NULL;
    ui_choosePanel2PriceSats = NULL;
    ui_choosePanel2PriceBrl = NULL;
    ui_choosePanel2PriceContainerBottom = NULL;
    ui_chooseBack = NULL;
    ui_chooseLogo = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;

}
