// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_CONFIG_H
#define UI_CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_config
extern void ui_config_screen_init(void);
extern void ui_config_screen_destroy(void);
extern lv_obj_t * ui_config;
extern lv_obj_t * ui_configPanel;
extern void ui_event_configButtonEspresso(lv_event_t * e);
extern lv_obj_t * ui_configButtonEspresso;
extern lv_obj_t * ui_configButtonEspressoLabel;
extern void ui_event_configButtonCoffee(lv_event_t * e);
extern lv_obj_t * ui_configButtonCoffee;
extern lv_obj_t * ui_configButtonCoffeeLabel;
extern void ui_event_configButtonReset(lv_event_t * e);
extern lv_obj_t * ui_configButtonReset;
extern lv_obj_t * ui_configButtonResetLabel;
extern void ui_event_configButtonBack(lv_event_t * e);
extern lv_obj_t * ui_configButtonBack;
extern lv_obj_t * ui_configButtonBackLabel;
extern void ui_event_configButtonRestart(lv_event_t * e);
extern lv_obj_t * ui_configButtonRestart;
extern lv_obj_t * ui_configButtonResetLabel1;
extern lv_obj_t * ui_configPasswordPanel;
extern lv_obj_t * ui_configPasswordLabel;
extern lv_obj_t * ui_configPasswordText;
extern void ui_event_configPasswordKeyboard(lv_event_t * e);
extern lv_obj_t * ui_configPasswordKeyboard;
extern void ui_event_configBack(lv_event_t * e);
extern lv_obj_t * ui_configBack;
extern void ui_event_configLogo(lv_event_t * e);
extern lv_obj_t * ui_configLogo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

