// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_CHOOSE_H
#define UI_CHOOSE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_choose
extern void ui_choose_screen_init(void);
extern void ui_choose_screen_destroy(void);
extern lv_obj_t * ui_choose;
extern lv_obj_t * ui_choosePanel1;
extern void ui_event_choosePanel1Button(lv_event_t * e);
extern lv_obj_t * ui_choosePanel1Button;
extern lv_obj_t * ui_choosePanel1ButtonLabel;
extern lv_obj_t * ui_choosePanel1Title;
extern lv_obj_t * ui_choosePanel1PriceLabel;
extern lv_obj_t * ui_choosePanel1PriceContainerTop;
extern lv_obj_t * ui_choosePanel1PriceSats;
extern lv_obj_t * ui_choosePanel1PriceBrl;
extern lv_obj_t * ui_choosePanel1PriceContainerBottom;
extern lv_obj_t * ui_choosePanel2;
extern void ui_event_choosePanel2Button(lv_event_t * e);
extern lv_obj_t * ui_choosePanel2Button;
extern lv_obj_t * ui_choosePanel2ButtonLabel;
extern lv_obj_t * ui_choosePanel2Title;
extern lv_obj_t * ui_choosePanel2PriceLabel;
extern lv_obj_t * ui_choosePanel2PriceContainerTop;
extern lv_obj_t * ui_choosePanel2PriceSats;
extern lv_obj_t * ui_choosePanel2PriceBrl;
extern lv_obj_t * ui_choosePanel2PriceContainerBottom;
extern void ui_event_chooseBack(lv_event_t * e);
extern lv_obj_t * ui_chooseBack;
extern void ui_event_chooseLogo(lv_event_t * e);
extern lv_obj_t * ui_chooseLogo;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

