// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t * ui_home;
extern void ui_event_homeLogo(lv_event_t * e);
extern lv_obj_t * ui_homeLogo;
extern lv_obj_t * ui_homeContainerTitle;
extern lv_obj_t * ui_homeTitle;
extern lv_obj_t * ui_homeSubTitle;
extern void ui_event_homeButton(lv_event_t * e);
extern lv_obj_t * ui_homeButton;
extern lv_obj_t * ui_homeButtonLabel;
extern lv_obj_t * ui_homeErrorPanel;
extern lv_obj_t * ui_homeErrorIcon;
extern lv_obj_t * ui_homeErrorTitle;
extern lv_obj_t * ui_homeErrorSubTitle;
extern void ui_event_homeConfig(lv_event_t * e);
extern lv_obj_t * ui_homeConfig;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

