// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#include "../ui.h"

lv_obj_t * ui_home = NULL;
lv_obj_t * ui_homeLogo = NULL;
lv_obj_t * ui_homeContainerTitle = NULL;
lv_obj_t * ui_homeTitle = NULL;
lv_obj_t * ui_homeSubTitle = NULL;
lv_obj_t * ui_homeButton = NULL;
lv_obj_t * ui_homeButtonLabel = NULL;
lv_obj_t * ui_homeErrorPanel = NULL;
lv_obj_t * ui_homeErrorIcon = NULL;
lv_obj_t * ui_homeErrorTitle = NULL;
lv_obj_t * ui_homeErrorSubTitle = NULL;
lv_obj_t * ui_homeConfig = NULL;
// event funtions
void ui_event_homeLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_choose, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_choose_screen_init);
    }
}

void ui_event_homeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_choose, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_choose_screen_init);
    }
}

void ui_event_homeConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        homeConfigClicked(e);
    }
}

// build funtions

void ui_home_screen_init(void)
{
    ui_home = lv_obj_create(NULL);
    lv_obj_add_flag(ui_home, LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_set_style_bg_color(ui_home, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeLogo = lv_img_create(ui_home);
    lv_img_set_src(ui_homeLogo, &ui_img_1238612230);
    lv_obj_set_width(ui_homeLogo, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_homeLogo, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_homeLogo, 499);
    lv_obj_set_y(ui_homeLogo, -48);
    lv_obj_add_flag(ui_homeLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_homeLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_homeLogo, 64);

    ui_homeContainerTitle = lv_obj_create(ui_home);
    lv_obj_remove_style_all(ui_homeContainerTitle);
    lv_obj_set_width(ui_homeContainerTitle, 752);
    lv_obj_set_height(ui_homeContainerTitle, 216);
    lv_obj_set_x(ui_homeContainerTitle, 0);
    lv_obj_set_y(ui_homeContainerTitle, 104);
    lv_obj_set_align(ui_homeContainerTitle, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_homeContainerTitle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeTitle = lv_label_create(ui_homeContainerTitle);
    lv_obj_set_width(ui_homeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_homeTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_homeTitle, "VIT Mitatronics");
    lv_obj_set_style_text_color(ui_homeTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeTitle, &ui_font_LoraRegular64, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeSubTitle = lv_label_create(ui_homeContainerTitle);
    lv_obj_set_width(ui_homeSubTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeSubTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_homeSubTitle, 0);
    lv_obj_set_y(ui_homeSubTitle, 83);
    lv_obj_set_align(ui_homeSubTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_homeSubTitle, "The Future of culinary excellence.");
    lv_obj_set_style_text_color(ui_homeSubTitle, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeSubTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_homeSubTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeSubTitle, &ui_font_OpenSansRegular20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButton = lv_btn_create(ui_homeContainerTitle);
    lv_obj_set_width(ui_homeButton, 204);
    lv_obj_set_height(ui_homeButton, 48);
    lv_obj_set_x(ui_homeButton, -2);
    lv_obj_set_y(ui_homeButton, 155);
    lv_obj_set_align(ui_homeButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_homeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_homeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeButton, lv_color_hex(0xF7AB14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_homeButton, lv_color_hex(0x008F85), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_homeButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_homeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_homeButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_homeButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_homeButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeButton, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeButtonLabel = lv_label_create(ui_homeButton);
    lv_obj_set_width(ui_homeButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_homeButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_homeButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_homeButtonLabel, "Browse Recipes");
    lv_obj_set_style_text_color(ui_homeButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeButtonLabel, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeErrorPanel = lv_obj_create(ui_home);
    lv_obj_set_width(ui_homeErrorPanel, 630);
    lv_obj_set_height(ui_homeErrorPanel, 80);
    lv_obj_set_x(ui_homeErrorPanel, 0);
    lv_obj_set_y(ui_homeErrorPanel, -45);
    lv_obj_set_align(ui_homeErrorPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_homeErrorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_homeErrorPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_homeErrorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_homeErrorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_homeErrorPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_homeErrorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_homeErrorPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_homeErrorPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_homeErrorPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_homeErrorPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeErrorIcon = lv_img_create(ui_homeErrorPanel);
    lv_img_set_src(ui_homeErrorIcon, &ui_img_water_png);
    lv_obj_set_width(ui_homeErrorIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_homeErrorIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_align(ui_homeErrorIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_homeErrorIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_homeErrorIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_homeErrorTitle = lv_label_create(ui_homeErrorPanel);
    lv_obj_set_width(ui_homeErrorTitle, 540);
    lv_obj_set_height(ui_homeErrorTitle, 20);
    lv_obj_set_align(ui_homeErrorTitle, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_homeErrorTitle, "Oops! The reservoir is empty");
    lv_obj_set_style_text_color(ui_homeErrorTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeErrorTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeErrorTitle, &ui_font_OpenSansSemiBold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeErrorSubTitle = lv_label_create(ui_homeErrorPanel);
    lv_obj_set_width(ui_homeErrorSubTitle, 540);
    lv_obj_set_height(ui_homeErrorSubTitle, 20);
    lv_obj_set_align(ui_homeErrorSubTitle, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_homeErrorSubTitle, "Please refill the required ingredients!");
    lv_obj_set_style_text_color(ui_homeErrorSubTitle, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_homeErrorSubTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_homeErrorSubTitle, &ui_font_OpenSansRegular16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_homeConfig = lv_imgbtn_create(ui_home);
    lv_imgbtn_set_src(ui_homeConfig, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_config_png, NULL);
    lv_imgbtn_set_src(ui_homeConfig, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_config_png, NULL);
    lv_obj_set_width(ui_homeConfig, 48);
    lv_obj_set_height(ui_homeConfig, 48);
    lv_obj_set_x(ui_homeConfig, -352);
    lv_obj_set_y(ui_homeConfig, -200);
    lv_obj_set_align(ui_homeConfig, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_homeLogo, ui_event_homeLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeButton, ui_event_homeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_homeConfig, ui_event_homeConfig, LV_EVENT_ALL, NULL);

}

void ui_home_screen_destroy(void)
{
    if(ui_home) lv_obj_del(ui_home);

    // NULL screen variables
    ui_home = NULL;
    ui_homeLogo = NULL;
    ui_homeContainerTitle = NULL;
    ui_homeTitle = NULL;
    ui_homeSubTitle = NULL;
    ui_homeButton = NULL;
    ui_homeButtonLabel = NULL;
    ui_homeErrorPanel = NULL;
    ui_homeErrorIcon = NULL;
    ui_homeErrorTitle = NULL;
    ui_homeErrorSubTitle = NULL;
    ui_homeConfig = NULL;

}
