// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_PREPARING_H
#define UI_PREPARING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_preparing
extern void ui_preparing_screen_init(void);
extern void ui_preparing_screen_destroy(void);
extern void ui_event_preparing(lv_event_t * e);
extern lv_obj_t * ui_preparing;
extern lv_obj_t * ui_preparingPanel;
extern void ui_event_preparingButton(lv_event_t * e);
extern lv_obj_t * ui_preparingButton;
extern lv_obj_t * ui_preparingButtonLabel;
extern lv_obj_t * ui_preparingTitle;
extern lv_obj_t * ui_bcPrepIcon;
extern lv_obj_t * ui_preparingProgress;
extern void ui_event_preparingLogo2(lv_event_t * e);
extern lv_obj_t * ui_preparingLogo2;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

