// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_PAYMENT_H
#define UI_PAYMENT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_payment
extern void ui_payment_screen_init(void);
extern void ui_payment_screen_destroy(void);
extern void ui_event_payment(lv_event_t * e);
extern lv_obj_t * ui_payment;
extern void ui_event_paymentBack(lv_event_t * e);
extern lv_obj_t * ui_paymentBack;
extern lv_obj_t * ui_paymentPanel;
extern lv_obj_t * ui_paymentTitle;
extern lv_obj_t * ui_paymentSubTitle;
extern lv_obj_t * ui_qrCodeContainer;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

