// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#include "../ui.h"

lv_obj_t * ui_payment = NULL;
lv_obj_t * ui_paymentBack = NULL;
lv_obj_t * ui_paymentPanel = NULL;
lv_obj_t * ui_paymentTitle = NULL;
lv_obj_t * ui_paymentSubTitle = NULL;
lv_obj_t * ui_qrCodeContainer = NULL;
// event funtions
void ui_event_payment(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_preparing, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_preparing_screen_init);
    }
}

void ui_event_paymentBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        paymentBackButtonClicked(e);
    }
}

// build funtions

void ui_payment_screen_init(void)
{
    ui_payment = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_payment, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_payment, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_paymentBack = lv_imgbtn_create(ui_payment);
    lv_imgbtn_set_src(ui_paymentBack, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_chevron_png, NULL);
    lv_imgbtn_set_src(ui_paymentBack, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_chevron_png, NULL);
    lv_obj_set_width(ui_paymentBack, 48);
    lv_obj_set_height(ui_paymentBack, 48);
    lv_obj_set_x(ui_paymentBack, -352);
    lv_obj_set_y(ui_paymentBack, -200);
    lv_obj_set_align(ui_paymentBack, LV_ALIGN_CENTER);

    ui_paymentPanel = lv_obj_create(ui_payment);
    lv_obj_set_width(ui_paymentPanel, 324);
    lv_obj_set_height(ui_paymentPanel, 263);
    lv_obj_set_x(ui_paymentPanel, -223);
    lv_obj_set_y(ui_paymentPanel, 2);
    lv_obj_set_align(ui_paymentPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_paymentPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_paymentPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_paymentPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_paymentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_paymentPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_paymentPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_paymentTitle = lv_label_create(ui_paymentPanel);
    lv_obj_set_width(ui_paymentTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_paymentTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_paymentTitle, 0);
    lv_obj_set_y(ui_paymentTitle, 28);
    lv_obj_set_align(ui_paymentTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_paymentTitle, "Payment");
    lv_obj_set_style_text_color(ui_paymentTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_paymentTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_paymentTitle, &ui_font_LoraRegular40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_paymentSubTitle = lv_label_create(ui_paymentPanel);
    lv_obj_set_width(ui_paymentSubTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_paymentSubTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_paymentSubTitle, -46);
    lv_obj_set_y(ui_paymentSubTitle, 110);
    lv_obj_set_align(ui_paymentSubTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_paymentSubTitle, "Mined in a radius\nReady in an instant");
    lv_obj_set_style_text_color(ui_paymentSubTitle, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_paymentSubTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_paymentSubTitle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_paymentSubTitle, &ui_font_OpenSansRegular20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_qrCodeContainer = lv_obj_create(ui_payment);
    lv_obj_remove_style_all(ui_qrCodeContainer);
    lv_obj_set_width(ui_qrCodeContainer, 408);
    lv_obj_set_height(ui_qrCodeContainer, 408);
    lv_obj_set_x(ui_qrCodeContainer, 158);
    lv_obj_set_y(ui_qrCodeContainer, -1);
    lv_obj_set_align(ui_qrCodeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_qrCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_qrCodeContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_qrCodeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_paymentBack, ui_event_paymentBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_payment, ui_event_payment, LV_EVENT_ALL, NULL);

}

void ui_payment_screen_destroy(void)
{
    if(ui_payment) lv_obj_del(ui_payment);

    // NULL screen variables
    ui_payment = NULL;
    ui_paymentBack = NULL;
    ui_paymentPanel = NULL;
    ui_paymentTitle = NULL;
    ui_paymentSubTitle = NULL;
    ui_qrCodeContainer = NULL;

}
