// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#ifndef UI_SUCCESS_H
#define UI_SUCCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_success
extern void ui_success_screen_init(void);
extern void ui_success_screen_destroy(void);
extern lv_obj_t * ui_success;
extern lv_obj_t * ui_successPanel;
extern lv_obj_t * ui_successPanelImage;
extern lv_obj_t * ui_successPanelTitle;
extern void ui_event_successPanelButton(lv_event_t * e);
extern lv_obj_t * ui_successPanelButton;
extern lv_obj_t * ui_successButtonLabel;
extern lv_obj_t * ui_logoSuccess;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

