// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: vitmitatronics

#include "../ui.h"

lv_obj_t * ui_success = NULL;
lv_obj_t * ui_successPanel = NULL;
lv_obj_t * ui_successPanelImage = NULL;
lv_obj_t * ui_successPanelTitle = NULL;
lv_obj_t * ui_successPanelButton = NULL;
lv_obj_t * ui_successButtonLabel = NULL;
lv_obj_t * ui_logoSuccess = NULL;
// event funtions
void ui_event_successPanelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        successPanelButtonClicked(e);
    }
}

// build funtions

void ui_success_screen_init(void)
{
    ui_success = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_success, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_success, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_successPanel = lv_obj_create(ui_success);
    lv_obj_set_width(ui_successPanel, 360);
    lv_obj_set_height(ui_successPanel, 372);
    lv_obj_set_align(ui_successPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_successPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_successPanel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_successPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_successPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_successPanel, lv_color_hex(0x4D4D4D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_successPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_successPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_successPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_successPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_successPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_successPanel, 16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_successPanelImage = lv_img_create(ui_successPanel);
    lv_img_set_src(ui_successPanelImage, &ui_img_check_png);
    lv_obj_set_width(ui_successPanelImage, LV_SIZE_CONTENT);   /// 132
    lv_obj_set_height(ui_successPanelImage, LV_SIZE_CONTENT);    /// 132
    lv_obj_set_x(ui_successPanelImage, 0);
    lv_obj_set_y(ui_successPanelImage, 32);
    lv_obj_set_align(ui_successPanelImage, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_successPanelImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_successPanelImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_successPanelTitle = lv_label_create(ui_successPanel);
    lv_obj_set_width(ui_successPanelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_successPanelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_successPanelTitle, 0);
    lv_obj_set_y(ui_successPanelTitle, 169);
    lv_obj_set_align(ui_successPanelTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_successPanelTitle, "Enjoy your Food Fiesta!");
    lv_obj_set_style_text_color(ui_successPanelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_successPanelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_successPanelTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_successPanelTitle, &ui_font_LoraRegular24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_successPanelButton = lv_btn_create(ui_successPanel);
    lv_obj_set_width(ui_successPanelButton, 328);
    lv_obj_set_height(ui_successPanelButton, 44);
    lv_obj_set_x(ui_successPanelButton, 0);
    lv_obj_set_y(ui_successPanelButton, 277);
    lv_obj_set_align(ui_successPanelButton, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_successPanelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_successPanelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_successPanelButton, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_successPanelButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_successPanelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_successPanelButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_successPanelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_successPanelButton, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_successPanelButton, &ui_font_OpenSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_successButtonLabel = lv_label_create(ui_successPanelButton);
    lv_obj_set_width(ui_successButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_successButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_successButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_successButtonLabel, "Finish (10s)");
    lv_obj_set_style_text_color(ui_successButtonLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_successButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_successButtonLabel, &ui_font_OpenSansBold20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logoSuccess = lv_img_create(ui_success);
    lv_img_set_src(ui_logoSuccess, &ui_img_1238612230);
    lv_obj_set_width(ui_logoSuccess, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_logoSuccess, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_logoSuccess, 508);
    lv_obj_set_y(ui_logoSuccess, -52);
    lv_obj_add_flag(ui_logoSuccess, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logoSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_logoSuccess, 64);

    lv_obj_add_event_cb(ui_successPanelButton, ui_event_successPanelButton, LV_EVENT_ALL, NULL);

}

void ui_success_screen_destroy(void)
{
    if(ui_success) lv_obj_del(ui_success);

    // NULL screen variables
    ui_success = NULL;
    ui_successPanel = NULL;
    ui_successPanelImage = NULL;
    ui_successPanelTitle = NULL;
    ui_successPanelButton = NULL;
    ui_successButtonLabel = NULL;
    ui_logoSuccess = NULL;

}
